# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Munch < Formula
  desc "Terminal UI for exploring an MCP server over streamable HTTP"
  homepage "https://github.com/nreidtwil/munch"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nreidtwil/homebrew-munch/releases/download/v0.1.0/munch_darwin_amd64.tar.gz"
      sha256 "bda576737366ac8731938380ef2993420a659ba3b44cfa8ca36070e4ee39786e"

      define_method(:install) do
        bin.install "munch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nreidtwil/homebrew-munch/releases/download/v0.1.0/munch_darwin_arm64.tar.gz"
      sha256 "88d843600f2e851292671747aa3079aa31aa8fcf60a93b9b5a73d36f355ed3cd"

      define_method(:install) do
        bin.install "munch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nreidtwil/homebrew-munch/releases/download/v0.1.0/munch_linux_amd64.tar.gz"
      sha256 "5235fbf3dffb27fc75575e36e4a0d73d004bb5c6f9f55bdf643e7061df9ce670"
      define_method(:install) do
        bin.install "munch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nreidtwil/homebrew-munch/releases/download/v0.1.0/munch_linux_arm64.tar.gz"
      sha256 "11fec7aa561ffd14af24a349722d32e796c2b2554407fa9b0ac12cdbdd5230da"
      define_method(:install) do
        bin.install "munch"
      end
    end
  end

  test do
    system "#{bin}/munch --help"
  end
end
